version: "3"

vars:
    DB_URL: postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable

tasks:


    createdb: 
        desc: Create simple_bank db
        cmds:
        - docker exec -it postgres14 createdb --username=root --owner=root simple_bank

    create-api-image:
        desc: Create simplebank image api
        cmds:
        - docker build -t simplebank:latest .


    dropdb:
        desc: Drop simple_bank db
        cmds:
        - docker exec -it postgres14 dropdb simple_bank


    lv: 
        desc: List docker host volume path
        cmds:
        - sudo ls -l /var/lib/docker/volumes/postgres/_data


    mup1:
        desc: Migrate up file 000001_init_schema.up.sql
        cmds:
        - migrate -path db/migration -database "{{.DB_URL}}" -verbose up

    mup2:
        desc: Migrate up file 000002_add_users
        cmds:
        - migrate -path db/migration -database "{{.DB_URL}}" -verbose up 1


    mdown1:
        desc: Migrate down file 000001_init_schema.down.sql
        cmds:
        - migrate -path db/migration -database "{{.DB_URL}}" -verbose down


    mdown2:
        desc: Migrate down file 000002_add_users
        cmds:
        - migrate -path db/migration -database "{{.DB_URL}}" -verbose down 1  

    postgres:
        desc: Start Postgress db
        cmds:
        - docker run --rm --name postgres14 --network simple-bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:14-alpine

    server:
        desc: Start server
        cmds:
        - go run main.go

    shell:
        desc: Shell into container
        cmds:
        - docker exec -it postgres14 /bin/sh


    sqlc: 
        desc: Generate sql codee
        cmds:
        - sqlc generate

    spostgres:
        desc: Start Postgress db with permanent storage
        cmds:
        - docker run --rm --name postgres14 --network simple-bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d -v postgres:/var/lib/postgresql/data postgres:14-alpine 

    sapi:
        desc: Start simplebank api image 
        cmds:
        - docker container run --rm --name simplebank --network simple-bank-network -p 8080:8080 -e GIN_MODE=release -e "DB_SOURCE=postgresql://root:secret@postgres14:5432/simple_bank?sslmode=disable" simplebank:latest

    test: 
        desc: Run test code
        cmds:
        - go test -v -cover ./...

    usedb:
        desc: Use simple_bank db
        cmds:
        - docker exec -it postgres14 psql -U root -d simple_bank


    di:
        desc: Test for interactive container
        cmds:
        - docker container run --rm -it simplebank sh
    

