name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    env:
      IMAGE_NAME: gcr.io/my-linux-project-348713/simple_bank

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'


      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - id: deploy
        name: Deploy Docker image
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: ${{ env.IMAGE_NAME }}
          region: us-central1
          service: simple_bank

      # - name: Test URL
      #   run: curl "${{ steps.deploy.outputs.url }}"
